version:  "3"

services:
  app:
    build: ./src

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginxfile:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - app
